name: "build-ms-test-dev"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild (x64)
      if: always()
      id: setup_msbuild_path_x64
      uses: ./
      with:
        vs-prerelease: true
        msbuild-architecture: 'x64'

    - name: echo msbuild path
      run: |
        echo "ARM PATH: ${{ steps.setup_msbuild_path_x64.outputs.msbuildPath }}"

    - name: echo MSBuild
      run: |
        msbuild -version
        nmake /?
        
