name: "build-ms-test-dev"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: echo MSBuild
      run: |
        msbuild -version
        nmake /?
        
